### ISSUE TITLE
Sensitive Info

### ISSUE THREAD

**Issue by RogueMaster** [kmal808/flip_the_world#3]
Your NFC folder has a credit card shared to the world it seems...

**Comment by kmal808** [comment]
Good looking out. Working on that right now. Where's GitGuardian when you need them 😶‍🌫️.

**Comment by RogueMaster** [comment]
I would recommend calling your CC company and getting a new #, good luck making it really go away with github

**Comment by kmal808** [comment]
It's a colleagues card deets lol. He didn't believe me that the flipper could clone and emulate. I did let him know to nuke that card tho. Appreciate ya.
